### ISSUE TITLE
submition error ECF_JOB_CMD

### ISSUE THREAD

**Issue by AlenaTrojakova** [destination-earth-digital-twins/DE330_Training_2024#4]
I experienced following error when trying to run suite CY48t3_AROME_DEMO_60x80_2500m.
 
```
024-06-14 12:26:54,919; troika.controllers.base; WARNING; Backup script file '/home/cza/deode_ecflow/jobout/CY48t3_AROME_DEMO_60x80_2500m/PreCleaning.job1.orig' already exists, overwriting
2024-06-14 12:26:55,173; troika.sites.base; ERROR; mkdir stderr:
b'Permission denied, please try again.\r\nPermission denied, please try again.\r\ncza@hpc-batch: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,hostbased).'
2024-06-14 12:26:55,174; troika.controllers.base; CRITICAL; Output directory creation failed with exit code 255
2024-06-14 12:26:55,286; troika.sites.base; ERROR; mkdir stderr:
b'Permission denied, please try again.\r\nPermission denied, please try again.\r\ncza@hpc-batch: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,hostbased).'
2024-06-14 12:26:55,287; troika.controllers.base; ERROR; Exception during teardown/exit
Traceback (most recent call last):
  File "/opt/troika/lib/python3.9/site-packages/troika/controllers/base.py", line 69, in submit
    hook.pre_submit(self.site, script, output, dryrun)
  File "/opt/troika/lib/python3.9/site-packages/troika/hooks/base.py", line 56, in __call__
    res = func(*args, **kwargs)
  File "/opt/troika/lib/python3.9/site-packages/troika/hooks/common.py", line 24, in create_output_dir
    ensure_output_dir(site, output, dryrun=dryrun)
  File "/opt/troika/lib/python3.9/site-packages/troika/hooks/common.py", line 11, in ensure_output_dir
    return site.create_output_dir(output, dryrun=dryrun)
  File "/opt/troika/lib/python3.9/site-packages/troika/sites/base.py", line 180, in create_output_dir
    check_retcode(proc.returncode, what="Output directory creation")
  File "/opt/troika/lib/python3.9/site-packages/troika/utils.py", line 81, in check_retcode
    raise RunError(msg)
troika.RunError: Output directory creation failed with exit code 255

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/troika/lib/python3.9/site-packages/troika/controllers/base.py", line 188, in __exit__
    self._controller.teardown(self.status)
  File "/opt/troika/lib/python3.9/site-packages/troika/controllers/base.py", line 228, in teardown
    hook.at_exit(self.args.action, self.site, self.args, sts, self.logfile)
  File "/opt/troika/lib/python3.9/site-packages/troika/hooks/base.py", line 56, in __call__
    res = func(*args, **kwargs)
  File "/opt/troika/lib/python3.9/site-packages/troika/hooks/common.py", line 40, in copy_submit_logfile
    out_dir = ensure_output_dir(site, args.output, dryrun=args.dryrun)
  File "/opt/troika/lib/python3.9/site-packages/troika/hooks/common.py", line 11, in ensure_output_dir
    return site.create_output_dir(output, dryrun=dryrun)
  File "/opt/troika/lib/python3.9/site-packages/troika/sites/base.py", line 180, in create_output_dir
    check_retcode(proc.returncode, what="Output directory creation")
  File "/opt/troika/lib/python3.9/site-packages/troika/utils.py", line 81, in check_retcode
    raise RunError(msg)
troika.RunError: Output directory creation failed with exit code 255


```

I'm not from the full ECMWF Member but I got access to HPC, I have msdeode group.
I have the specific ecflow server name but I define it in [scheduler.ecfvars]

 `  ecf_host = "ecfg-@USER@-1"`

I managed to run a simple SLUM job. 
File: /home/cza/deode_ecflow/jobout/CY48t3_AROME_DEMO_60x80_2500m/PreCleaning.job1.submitlog Size: 3 KB Modified: 2024-06-14 12:26:55
Source: read from disk at 2024-06-14  12:29:19

**Comment by FlorianW-ZAMG** [comment]
Looks like you are not allowed to ssh to hpc-batch. You can run `ssh-key-setup` which should setup the proper ssh keys for a number of hosts. Can you try to run this command and check whether you can run ssh `hpc-batch` without typing a password? If so, you can retry to run the suite

**Comment by AlenaTrojakova** [comment]
It works ! Thanks a lot.
