### ISSUE TITLE
Starting  the deode ecflow suite

### ISSUE THREAD

**Issue by iljamal** [destination-earth-digital-twins/DE330_Training_2024#5]
I have issue with python not finding ecflow module during deode suitr start ...

I have these modules loaded:
module load python3/3.10.10-01
module load ecflow

and deode_ui   GUI loads  well
but

deode start suite
2024-06-17 10:00:46 | INFO     | Start deode v0.5.0 --> "deode start suite"
2024-06-17 10:00:47 | INFO     | Set basetime to 2023-09-16T00:00:00Z
2024-06-17 10:00:47 | INFO     | Set validtime to 2023-09-16T00:00:00Z
2024-06-17 10:00:47 | INFO     | Starting suite...
2024-06-17 10:00:47 | INFO     | Config file: /etc/ecmwf/nfs/dh1_home_b/eeim/Deode-Workflow/deode/data/config_files/config.toml
2024-06-17 10:00:47 | INFO     | Ecflow settings: 
2024-06-17 10:00:47 | INFO     | ecf_host: ecflow-gen-eeim-001
2024-06-17 10:00:47 | INFO     | ecf_jobout: /home/eeim/deode_ecflow/jobout
2024-06-17 10:00:47 | INFO     | ecf_files: /home/eeim/deode_ecflow/ecf_files
2024-06-17 10:00:47 | INFO     | ecf_files_remotely: /home/eeim/deode_ecflow/ecf_files
2024-06-17 10:00:47 | INFO     | ecf_home: /home/eeim/deode_ecflow/jobout
2024-06-17 10:00:47 | INFO     | ecf_user: 
2024-06-17 10:00:47 | INFO     | ecf_remoteuser: 
2024-06-17 10:00:47 | INFO     | suite definition: DeodeSuiteDefinition
Traceback (most recent call last):
  File "/home/eeim/mambaforge/envs/cmc-beta/bin/deode", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/eeim/Deode-Workflow/deode/logs.py", line 106, in wrapper
    function_rtn = function(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/eeim/Deode-Workflow/deode/__main__.py", line 27, in main
    args.run_command(args=args, config=config)
  File "/etc/ecmwf/nfs/dh1_home_b/eeim/Deode-Workflow/deode/commands_functions.py", line 195, in start_suite
    server = EcflowServer(config, start_command=args.start_command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/eeim/Deode-Workflow/deode/scheduler.py", line 97, in __init__
    raise ModuleNotFoundError("Ecflow not found")
ModuleNotFoundError: Ecflow not found

**Comment by iljamal** [comment]
Solved ... somehow 
Had to shake off previous mambaforge   py environment    and re-install from clear?  py environment.

**Comment by FlorianW-ZAMG** [comment]
Okay, so the different python installations somehow interfered with each other? Might be something we can try to avoid in the workflow.
